local T = {}

T.Base = "base"
T.Name = "Interiors.Default"
T.ID = "default"

T.Versions = {
    main = { id = "default", },
    randomize = false,
    other = {
        {
            id = "default_cl",
            name = "Interiors.Default.Versions.ClassicDoors",
        },
    },
}

T.Interior = {

    Model = "models/molda/toyota_int/interior.mdl",

    Size = {
        Min = Vector(-585.336, -1378.008, -33.179),
        Max = Vector(892.477, 457.64, 381.653)
    },

    ExitBox = {
        Min = Vector(-659.914, -1364.271, -104.82),
        Max = Vector(984.983, 514.944, 385.095)
    },

    Portal = { -- Generated by portals debug tool
        pos = Vector(-326.12, 0, 138.900390625),
        ang = Angle(-0, 0, 0),
        width = 50,
        height = 92,
        thickness = -5,
    },

    Fallback={
        pos=Vector(-280,0,100),
        ang=Angle(0,0,0)
    },

    LightOverride = TARDIS.IntModules["default_lightoverride"],

    Light = TARDIS.IntModules["default_light_main"],

    Lights={
        console_white = TARDIS.IntModules["default_light_console_white"],
        console_bottom = TARDIS.IntModules["default_light_console_bottom"],
    },

    Sounds = {
        Teleport = {
            demat = "p00gie/tardis/default/demat_int.ogg",
            mat = "p00gie/tardis/default/mat_int.ogg",
            fullflight = "p00gie/tardis/default/full_int.ogg",
            demat_fail = "p00gie/tardis/default/demat_fail.ogg",
            demat_hads = "p00gie/tardis/demat_hads.wav",
            interrupt = "p00gie/tardis/default/demat_interrupt.ogg",
        },
        FlightLoop = "p00gie/tardis/default/flight_loop.wav",
    },

    IdleSound={
        {
            path="p00gie/tardis/default/hum.wav",
            volume=0.3
        }
    },

    Seats = {
        { pos = Vector(9, -154., 105), ang = Angle(0,0,0), },
        { pos = Vector(-134, -77, 105), ang = Angle(0,-65,0), },
        { pos = Vector(40, 147, 105), ang = Angle(0,170,0), },
        { pos = Vector(150, 26, 105), ang = Angle(0,100,0), },
    },

    Scanners = TARDIS.IntModules["default_scanners"],
    Screens = TARDIS.IntModules["default_screens"],

    Parts = TARDIS.IntModules["default_parts"],
    Controls = TARDIS.IntModules["default_controls"],
    PartTips = TARDIS.IntModules["default_part_tips"],
    CustomTips = TARDIS.IntModules["default_custom_tips"],

    TipSettings = {
        view_range_min = 40,
        view_range_max = 75,
    },

}

T.Exterior = {
    Sounds = {
        Spawn = "drmatt/tardis/repairfinish.wav",
        Delete = "p00gie/tardis/tardis_delete.wav",
    },
}

T.Timings = {
    DematAbortState = 3,
    TakeOffState = 3,
    ParkingState = 3.2,
}

T.CustomHooks = {
    screen_disable = TARDIS.IntModules["default_hook_screen_disable"],
}

T.CustomControls = {
    toggle_screen_1 = TARDIS.IntModules["default_control_toggle_screen_1"],
    toggle_screen_2 = TARDIS.IntModules["default_control_toggle_screen_2"],

    toggle_doorframe_light = {
        int_func=function(self,ply,part)
            local doorframe = self:GetPart("default_doorframe")
            doorframe:SetBodygroup(1,part:GetOn() and 0 or 1)
        end,
        power_independent = false,
        screen_button = false,
        tip_text = nil, -- let this one be an easter-egg-ish feature for now
    },
}

T.CustomSettings = {
    color = {
        text = "Interiors.Default.CustomSettings.Color",
        value_type = "list",
        value = "dynamic",
        options = {
            ["dynamic"] = "Interiors.Default.CustomSettings.Color.Dynamic",
            ["blue"] = "Interiors.Default.CustomSettings.Color.Blue",
            ["green"] = "Interiors.Default.CustomSettings.Color.Green",
            ["turquoise"] = "Interiors.Default.CustomSettings.Color.Turquoise",
            ["random"] = "Interiors.Default.CustomSettings.Color.Random",
        },
    },
    lamps = {
        text = "Interiors.Default.CustomSettings.Lamps",
        value_type = "bool",
        value = true,
    },
    small_version = {
        text = "Interiors.Default.CustomSettings.SmallVersion",
        value_type = "bool",
        value = false,
    },
    screens_off = {
        text = "Interiors.Default.CustomSettings.ScreensOff",
        value_type = "bool",
        value = false,
    },
    classic_doors_button = {
        text = "Interiors.Default.CustomSettings.ClassicDoorsButton",
        value_type = "bool",
        value = false,
    },
}

T.Templates = {
    default_exterior = { override = true, },
    default_lamps = {
        override = true,
        condition = function(id, ply, ent)
            return TARDIS:GetCustomSetting(id, "lamps", ply)
        end,
    },
    default_dynamic_color = {
        override = true,
        condition = function(id, ply, ent)
            local setting_val = TARDIS:GetCustomSetting(id, "color", ply)
            return (setting_val == "dynamic")
        end,
    },
    default_fixed_color = {
        override = true,
        condition = function(id, ply, ent)
            local setting_val = TARDIS:GetCustomSetting(id, "color", ply)
            return (setting_val ~= "dynamic")
        end,
    },

    default_small_version = {
        override = true,
        condition = function(id, ply, ent)
            return TARDIS:GetCustomSetting(id, "small_version", ply)
        end,
    },
    default_screens_off = {
        override = true,
        condition = function(id, ply, ent)
            return TARDIS:GetCustomSetting(id, "screens_off", ply)
        end,
    },
    default_screens_on = {
        override = true,
        condition = function(id, ply, ent)
            return not TARDIS:GetCustomSetting(id, "screens_off", ply)
        end,
    },
    default_small_version_lamp_fix= {
        override = true,
        condition = function(id, ply, ent)
            local lamps = TARDIS:GetCustomSetting(id, "lamps", ply)
            local small = TARDIS:GetCustomSetting(id, "small_version", ply)
            return (lamps and small)
        end,
    },
}
T.TemplatesMergeOrder = {
    "default_lamps",
    "default_more_lamps",
}

TARDIS:AddInterior(T)






local T = {}

T.Base = "default"
T.Name = "Interiors.Default"
T.ID = "default_cl"

T.EnableClassicDoors = true
T.IsVersionOf = "default"

T.Interior = {
    Fallback = { pos = Vector(-320, 0, 100), },

    Portal = {
        -- Generated by portals debug tool
        pos = Vector(-383.48433620246, 0, 145.419),
        ang = Angle(-0, 0, 0),
        width = 73.255813953488,
        height = 103.48837209302,
        thickness = -5,
    },

    Parts = {
        intdoor = {
            model = "models/parar020100/toyota_int/classic_doors.mdl",
            pos = Vector(-343.701, 0, 95.02),
            ang = Angle(0,0,0),
        },

        default_entry = {
            model = "models/parar020100/toyota_int/classic_doors_entry.mdl",
        },
        default_doorframe = false,
        default_door_button = { pos = Vector(-345.457, 30.183, 145.419), },
    },
    Controls = {
        default_door_button = "door",
    },

    Sounds = {
        Door={
            enabled=true,
            open="karmal/toyota_int/intdoor.wav",
            close="karmal/toyota_int/intdoor.wav",
        },
    },
    IntDoorAnimationTime = 3.5,
}

T.Exterior = {}

T.Templates = {
    default_exterior = false,
    exterior_ttcapsule_type50 = {override = true,}
}


T.CustomHooks = {
    doorframe_init = {
        inthooks = {
            ["PostInitialize"] = true,
        },
        func = function(ext,int)
            if CLIENT then return end
            local button_on = TARDIS:GetCustomSetting(ext.metadata.ID, "classic_doors_button", ext)
            local entry_part = int:GetPart("default_entry")

            if not IsValid(entry_part) then return end

            entry_part:SetBodyGroups(button_on and "11" or "00")
            int:SetPartInvisible("default_door_button", not button_on)

            local button = int:GetPart("default_door_button")
            if IsValid(button) then
                button:SetCollide(button_on, true)
            end
        end,
    },
    doorframe_sync = {
        inthooks = {
            ["PartBodygroupChanged"] = true,
        },
        func = function(ext, int, ent, bodygroup, value)
            if CLIENT then return end
            if ent == int:GetPart("default_entry") then
                local other = (bodygroup + 1) % 2
                if ent:GetBodygroup(other) ~= value then
                    ent:SetBodygroup(other, value)

                    local pipes = (value == 0)

                    local button = int:GetPart("default_door_button")
                    if IsValid(button) then
                        button:SetInvisible(pipes)
                        button:SetCollide(not pipes, true)
                    end
                end
            end
        end,
    },
}

TARDIS:AddInterior(T)
